(dataset)StatisticsTrain:
  class: NormalizationStatistics
  in: (in_task)->train
  by: global
  column: !var features
  axis: !var normalization_axis
(dataset)StatisticsValidation:
  class: Identity
  in: (dataset)StatisticsTrain->out
(dataset)StatisticsTest:
  class: Identity
  in: (dataset)StatisticsTrain->out
include:
- config: ../models/models.yaml
  dataset: (dataset)
  in_task: (dataset)Statistics
  model_mods: (model_mods)