(dataset)StatisticsTrain:
  class: NormalizationStatistics
  in: (in_task)->train
  by: !var (dataset)_normalize_by
  column: !var features
  axis: !var normalization_axis
(dataset)StatisticsValidation:
  class: NormalizationStatistics
  in: (in_task)->validation
  by: !var (dataset)_normalize_by
  column: !var features
  axis: !var normalization_axis
(dataset)StatisticsTest:
  class: NormalizationStatistics
  in: (in_task)->test
  by: !var (dataset)_normalize_by
  column: !var features
  axis: !var normalization_axis
include:
- config: ../models/models.yaml
  dataset: (dataset)
  in_task: (dataset)Statistics
  model_mods: (model_mods)