(dataset)Split:
  class: GroupSplit
  in: (in_task)->out
  column: partition
  group_column: !var (dataset)_group_column
  splits: !var (dataset)_group_splits
  export: True
  in_memory: !nocache True
  cache: False
(dataset)Partition:
  class: Split
  in: (dataset)Split->out
  split_col: partition
  in_memory: !nocache True
include:
- config: ../features/normalize.yaml
  dataset: (dataset)
  in_task: (dataset)Partition
  model_mods: (dataset)Metrics/labels=(dataset)OneHot->labels&(dataset)TrainGenerator/batch_task=(dataset)DataProcessor->out&(dataset)ValidationGenerator/batch_task=(dataset)DataProcessor->out&(dataset)TestGenerator/batch_task=(dataset)DataProcessor->out