modules:
- tasks
global:
  cache_path: s3://lpepino-datasets2/paper_experiments/cache
  dataset: [ravdess, iemocap]
  features: opensmile
  model: dienen_classifier
  
  Ravdess_model_max_seqlen: 250 #5 s
  IEMOCAP_model_max_seqlen: 750 #15 s
  IEMOCAP_partition: leave_one_out

  dienen_config: !yaml experiments/configs/dienen/mean_mlp.yaml
  batch_x: [audio,mask]
  batch_y: targets
  batch_size: 32
  n_epochs: 100

  data_processing_config: ../batch/os_sequence_embedding.yaml
  wandb_run: WANDBExperiment->out

include:
- config: ../datasets/datasets.yaml

Tasks:
  WANDBExperiment:
    class: WANDBExperiment
    project_name: w2v_ser
    experiment_name: ravdess_test
    description: Testing system in RAVDESS
    run_first: !nocache True
    cache: False