defaults:
  Ravdess_partition: group_split
  Ravdess_split_proportion_train: 0.7
  Ravdess_split_proportion_validation: 0.1
  Ravdess_split_proportion_test: 0.2
  Ravdess_group_column: actor
  Ravdess_group_splits:
    train: ['01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20']
    validation: ['21','22']
    test: ['23','24']
  Ravdess_normalize_by: actor
  Ravdess_leaveoneout_group: actor
  Ravdess_relabel_calm: '01' #(neutral)
  Ravdess_emotions: null
  Ravdess_dienen_mod: dienen_config/Model/Training/schedule/WANDBLogger/loggers/TrainMetrics/prefix=Ravdess

Tasks:
  DownstreamRavdess:
    class: TaskGraph
    cache: False
    in:
      wandb: !var wandb_run
    Tasks:
      RavdessDownloader:
        class: Downloader
        in_memory: True
        downloads:
        - SourcePath: s3://lpepino-datasets2/datasets/ravdess.zip
          DestinationPath: ~/Datasets/RAVDESS/ravdess.zip
          Extract: True
      RavdessReader:
        class: AudioDatasetFromDirectory
        run_after: RavdessDownloader->out
        dataset_path: ~/Datasets/RAVDESS
        filename_re: (?P<modality>\d*)-(?P<vocal_channel>\d*)-(?P<emotion>\d*)-(?P<emotional_intensity>\d*)-(?P<statement>\d*)-(?P<repetition>\d*)-(?P<actor>\d*).wav
      RavdessRelabelCalm:
        class: Relabel
        in: RavdessReader->out
        relabels:
        - column: emotion
          old_name: '02'
          new_name: !var Ravdess_relabel_calm
        in_memory: True
      RavdessFilterEmotions:
        class: Filter
        in: RavdessRelabelCalm->out
        column: emotion
        include_values: !var Ravdess_emotions
        in_memory: True
      RavdessLabelEncode:
        class: LabelEncoder
        column: emotion
        new_column: classID
        in: RavdessFilterEmotions->out
        in_memory: True
      include:
      - config: ../features/features.yaml
        dataset: Ravdess
        in_task: RavdessLabelEncode
      - config: ../features/merge_features.yaml
        dataset: Ravdess
      - config: !var data_processing_config
        dataset: Ravdess
        n_classes: 7